# Generated by Django 3.1 on 2021-11-13 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date Time de la creacion del objeto', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date Time de la ultima modificacion del objeto', verbose_name='modified at')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='La fila esta activa o no', verbose_name='is active')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('date_to_finish', models.DateTimeField(blank=True, null=True, verbose_name='Fecha a cumplir')),
                ('is_finalize', models.BooleanField(blank=True, default=False, verbose_name='Finalizado?')),
                ('color', models.CharField(blank=True, choices=[('C1', '#f22c2b'), ('C2', '#71db7a'), ('C3', '#395fd0')], default='C2', max_length=2, verbose_name='Color')),
                ('priority', models.CharField(blank=True, choices=[('P1', 'Muy importante'), ('P2', 'Medianamente importante'), ('P3', 'Poco importante')], default='P2', max_length=2, verbose_name='Prioridad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', 'modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
