version: '3'

volumes:
  todo_postgres_data: {}

services:
  challenge: &challenge
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: todo-challenge
    depends_on:
      - postgres
    env_file:
      - ./.envs/.postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data