version: '3'

services:
  sqlite3:
    container_name: sqlite3_container
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - /sqlite3:/root/db/
    ports:
      - '8000:8000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
