version: '3'

volumes:
  todo_postgres_data: {}

services:
  challenge: &challenge
    build:
      context: .
      dockerfile: ./compose/Dockerfile
    image: todo-challenge
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=todo
      - POSTGRES_USER=todo
      - POSTGRES_PASSWORD=1234
    volumes:
      - todo_postgres_data:/var/lib/postgresql/data