# Generated by Django 4.0.3 on 2022-08-07 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
    ]
